## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [5]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
0,0,Hobart,AU,2020-11-07 18:29:16,-42.88,147.33,42.01,86,0,9.17,clear sky
1,1,Saint-Philippe,RE,2020-11-07 18:31:51,-21.36,55.77,73.40,78,75,17.22,broken clouds
2,2,Thompson,CA,2020-11-07 18:31:51,55.74,-97.86,17.60,85,90,2.24,light snow
3,3,Gorin,RU,2020-11-07 18:31:51,51.20,136.67,19.67,90,100,5.86,overcast clouds
4,4,New Norfolk,AU,2020-11-07 18:31:13,-42.78,147.06,42.01,72,6,2.57,clear sky

In [6]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [8]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
6,6,Biak,ID,2020-11-07 18:31:52,-0.91,122.88,77.50,74,92,6.02,light rain
8,8,Kirakira,SB,2020-11-07 18:31:52,-10.45,161.92,78.84,82,42,5.12,light rain
18,18,Porto Novo,BJ,2020-11-07 18:31:53,6.50,2.60,80.60,83,40,10.29,scattered clouds
21,21,Sampit,ID,2020-11-07 18:31:54,-2.53,112.95,75.22,96,79,1.07,heavy intensity rain
26,26,San Cristobal,VE,2020-11-07 18:28:08,7.77,-72.22,84.20,70,40,16.11,scattered clouds

In [9]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()


# If you have some rows with null values, you'll need to 
# drop them using the dropna() method at the end of your 
# filtering statement when you are creating the new DataFrame.

City_ID                227
City                   227
Country                224
Date                   227
Lat                    227
Lng                    227
Max Temp               227
Humidity               227
Cloudiness             227
Wind Speed             227
Weather Description    227
dtype: int64

In [13]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna(how = "any")
clean_df.count()

City_ID                224
City                   224
Country                224
Date                   224
Lat                    224
Lng                    224
Max Temp               224
Humidity               224
Cloudiness             224
Wind Speed             224
Weather Description    224
dtype: int64

In [16]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Weather Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
6,Biak,ID,77.50,light rain,-0.91,122.88,
8,Kirakira,SB,78.84,light rain,-10.45,161.92,
18,Porto Novo,BJ,80.60,scattered clouds,6.50,2.60,
21,Sampit,ID,75.22,heavy intensity rain,-2.53,112.95,
26,San Cristobal,VE,84.20,scattered clouds,7.77,-72.22,
28,Kapaa,US,78.80,scattered clouds,22.08,-159.32,
30,Caravelas,BR,81.12,moderate rain,-17.71,-39.25,
31,Salalah,OM,77.00,clear sky,17.02,54.09,
35,Takoradi,GH,79.23,light rain,4.88,-1.76,
37,Am Timan,TD,82.13,clear sky,11.03,20.28,

In [17]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"] 
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
#     and 
    # 7. Drop the rows where there is no Hotel Name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [19]:
hotel_df.count()

City                   224
Country                224
Max Temp               224
Weather Description    224
Lat                    224
Lng                    224
Hotel Name             224
dtype: int64

In [23]:
clean_hotel_df = hotel_df

# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [24]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [27]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))